/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package androidx.vectordrawable;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f03002c;
        public static final int font = 0x7f0300fb;
        public static final int fontProviderAuthority = 0x7f0300fd;
        public static final int fontProviderCerts = 0x7f0300fe;
        public static final int fontProviderFetchStrategy = 0x7f0300ff;
        public static final int fontProviderFetchTimeout = 0x7f030100;
        public static final int fontProviderPackage = 0x7f030101;
        public static final int fontProviderQuery = 0x7f030102;
        public static final int fontStyle = 0x7f030103;
        public static final int fontVariationSettings = 0x7f030104;
        public static final int fontWeight = 0x7f030105;
        public static final int ttcIndex = 0x7f03025e;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f05006a;
        public static final int notification_icon_bg_color = 0x7f05006b;
        public static final int ripple_material_light = 0x7f050077;
        public static final int secondary_text_default_material_light = 0x7f050079;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f060051;
        public static final int compat_button_inset_vertical_material = 0x7f060052;
        public static final int compat_button_padding_horizontal_material = 0x7f060053;
        public static final int compat_button_padding_vertical_material = 0x7f060054;
        public static final int compat_control_corner_material = 0x7f060055;
        public static final int compat_notification_large_icon_max_height = 0x7f060056;
        public static final int compat_notification_large_icon_max_width = 0x7f060057;
        public static final int notification_action_icon_size = 0x7f0600c3;
        public static fin