/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package androidx.recyclerview;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f03002c;
        public static final int coordinatorLayoutStyle = 0x7f0300ac;
        public static final int fastScrollEnabled = 0x7f0300f4;
        public static final int fastScrollHorizontalThumbDrawable = 0x7f0300f5;
        public static final int fastScrollHorizontalTrackDrawable = 0x7f0300f6;
        public static final int fastScrollVerticalThumbDrawable = 0x7f0300f7;
        public static final int fastScrollVerticalTrackDrawable = 0x7f0300f8;
        public static final int font = 0x7f0300fb;
        public static final int fontProviderAuthority = 0x7f0300fd;
        public static final int fontProviderCerts = 0x7f0300fe;
        public static final int fontProviderFetchStrategy = 0x7f0300ff;
        public static final int fontProviderFetchTimeout = 0x7f030100;
        public static final int fontProviderPackage = 0x7f030101;
        public static final int fontProviderQuery = 0x7f030102;
        public static final int fontStyle = 0x7f030103;
        public static final int fontVariationSettings = 0x7f030104;
        public static final int fontWeight = 0x7f030105;
        public static final int keylines = 0x7f030137;
        public static final int layoutManager = 0x7f03013c;
        public static final int layout_anchor = 0x7f03013d;
        public static final int layout_anchorGravity = 0x7f03013e;
        public static final int layout_behavior = 0x7f03013f;
        public static final int layout_dodgeInsetEdges = 0x7f03016b;
        public static final int layout_insetEdge = 0x7f030174;
        public static final int layout_keyline = 0x7f030175;
        public static final int reverseLayout = 0x7f0301cb;
        public static final int spanCount = 0x7f0301e6;
        public static final int stackFromEnd = 0x7f0301ec;
        public static final int statusBarBackground = 0x7f0301f3;
        public static final int ttcIndex = 0x7f03025e;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f05006a;
        public static final int notification_icon_bg_color = 0x7f05006b;
        public static final int ripple_material_light = 0x7f050077;
        public static final int secondary_text_default_material_light = 0x7f050079;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f060051;
        public static final int compat_button_inset_vertical_material = 0x7f060052;
        public static final int compat_button_padding_horizontal_material = 0x7f060053;
        public static final int compat_button_padding_vertical_material = 0x7f060054;
        public static final int compat_control_corner_material = 0x7f060055;
        public static final int compat_notification_large_icon_max_height = 0x7f060056;
        public static final int compat_notification_large_icon_max_width = 0x7f060057;
        public static final int fastscroll_default_thickness = 0x7f060086;
        public static final int fastscroll_margin = 0x7f060087;
        public static final int fastscroll_minimum_range = 0x7f060088;
        public static final int item_touch_helper_max_drag_scroll_per_frame = 0x7f060090;
        public static final int item_touch_helper_swipe_escape_max_velocity = 0x7f060091;
        public static final int item_touch_helper_swipe_escape_velocity = 0x7f060092;
        public static final int notification_action_icon_size = 0x7f0600c3;
        public static final int notification_action_text_size = 0x7f0600c4;
        public static final int notification_big_circle_margin = 0x7f0600c5;
        public static final int notification_content_margin_start = 0x7f0600c6;
        public static final int notification_large_icon_height = 0x7f0600c7;
        public static final int notification_large_icon_width = 0x7f0600c8;
        public static final int notification_main_column_padding_top = 0x7f0600c9;
        public static final int notification_media_narrow_margin = 0x7f0600ca;
        public static final int notification_right_icon_size = 0x7f0600cb;
        public static final int notification_right_side_padding_top = 0x7f0600cc;
        public static final int notification_small_icon_background_padding = 0x7f0600cd;
        public static final int notification_small_icon_size_as_large = 0x7f0600ce;
        public static final int notification_subtext_size = 0x7f0600cf;
        public static final int notification_top_pad = 0x7f0600d0;
        public static final int notification_top_pad_large_text = 0x7f0600d1;
    }
    public static final class drawable {
        private drawable() {}

        public static final int notification_action_background = 0x7f070079;
        public static final int notification_bg = 0x7f07007a;
        public static final int notification